name: Actions en GitHub
on: push

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar contenido del directorio 
        run: |
          ls -la
      - name: Clonar Repositorio
        uses: actions/checkout@v2
      - name: Mostrar contenido del directorio Después
        run: |
          ls -la
      - name: Crear Archivo Random
        run: |
          git config --global user.email "oscortiz@gmail.com"
          git config --global user.name "oscortiz"
          echo $RANDOM >> random.txt
          git add random.txt
          git commit -m "Añadido Random File"
          git push     

