name: Variables de Entorno
on: push

env:
  WF_ENV: Disponible en todos los jobs

jobs:
  log-env: 
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Disponible en todos los stepsde log-env
    steps:
      - name: Log Variables Entorno
        env:
          STEP_ENV: Disponible para este step
        run: |
          echo "WF_ENF: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
  log-defult-env:
    runs-on: ubuntu-latest
    steps:
      - name: Log Variables GitHub
        run: |
          echo "HOME: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "WF_ENF: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"  
          