name: Comandos de shell
on: #[push]
  #schedule:
  #  - cron: "*/2 * * * *"
  repository_dispatch:
    types: [desde_curl]
jobs:
  ejecutar-comandos-shell:
    runs-on: ubuntu-latest
    steps:
      - name: echo cadena 
        run: echo "Hello World"
      - name: scripts multilinea
        run: |
          node -v
          npm -v
          ls -la
          cat /etc/os-release
      - name: python command
        shell: python
        run: |
          import platform
          print(platform.processor())          
  comandos-windows:
    runs-on: windows-latest
    steps:
      - name: PowerShell
        run: Get-Location
      - name: bash
        run: pwd
